import React, { useState, useEffect } from 'react';

import Link from 'next/link';

import getSettings from '../../../utils/get-settings';

import { Theme } from '../../../types/settings';

import Header from '../../../components/Header';
import MetaData from '../../../components/MetaData';

const ApiDocsV1 = () => {
    const [theme, setTheme] = useState<Theme>('system');
    useEffect(() => {
        (async () => {
            const settings = await getSettings();
            setTheme(settings.theme);
        })();
    }, []);
    useEffect(() => {
        document.querySelector('html')!.classList.remove('dark', 'light');

        if (theme === 'system') {
            const newTheme = window.matchMedia('(prefers-color-scheme: light)').matches ? 'light' : 'dark';
            document.querySelector('html')!.classList.add(newTheme);
        } else {
            document.querySelector('html')!.classList.add(theme);
        }
    }, [theme]);

    return (
        <div>
            <MetaData page="api-docs" apiPage="rest" apiVersion="v1" />
            <Header page="api-docs" apiPage="rest" apiVersion="v1" />
            <main>
                <section id="user" className="user p-2">
                    <h2 className="font-bold text-2xl"><code>/api/v1/user</code></h2>
                    <section>
                        <h3 className="font-bold text-lg"><code>GET</code></h3>
                        <section className="description p-2">
                            <h4 className="font-bold">Description</h4>
                            <p className="description">Get a Todite users ID, Firebase UID and their settings</p>
                        </section>
                        <section className="headers p-2">
                            <h4 className="font-bold">Headers</h4>
                            <ul>
                                <li>
                                    <code>Authorization</code> - The authorization token generated by Firebase by running <code>user.getIdToken()</code>. <b className="font-bold">Note: This should only be used internally within the app</b>
                                </li>
                            </ul>
                        </section>
                        <section className="query-parameters p-2">
                            <h4 className="font-bold">Query Parameters</h4>
                            <ul>
                                <li>
                                    <code>api_key</code> - <Link href="/docs/api-key"><a className="text-blue-600 hover:underline focus:underline">Your API key</a></Link>
                                </li>
                            </ul>
                        </section>
                        <section className="data-structure p-2">
                            <h4 className="font-bold">Data Structure</h4>
                            <p>This API endpoint returns an object with this data structure:</p>
                            <ul>
                                <li>
                                    <code>_id</code> - <code>string</code> - The user's ID (generated by MongoDB)
                                </li>
                                <li>
                                    <code>uid</code> - <code>string</code> - The user's Firebase UID
                                </li>
                                <li>
                                    <code>settings</code> - <code>object</code> (below)
                                    <ul className="p-2">
                                        <li>
                                            <code>theme</code> - <code>string ("dark" | "light" | "system")</code> - The user's preferred theme
                                        </li>
                                        <li>
                                            <code>deleteTodoOnCompleted</code> - <code>boolean</code> - Whether the user wants to-dos to be automatically deleted when they have been completed
                                        </li>
                                        <li>
                                            <code>syncSettings</code> - <code>boolean</code> - Whether the user wants to sync their settings on all devices they sign in on
                                        </li>
                                    </ul>
                                    - The user's site settings
                                </li>
                            </ul>
                        </section>
                        <section className="errors p-2">
                            <h4 className="font-bold">Errors</h4>
                            <p>You may get this error in an <code>error</code> object</p>
                            <ul>
                                <li>
                                    <code>status</code> - <code>number (404)</code> - The HTTP status code (in a <code>GET</code> request, it can <i>only</i> be <code>404</code>)
                                </li>
                                <li>
                                    <code>message</code> - <code>string</code> - An error message
                                </li>
                            </ul>
                        </section>
                    </section>
                    <section>
                        <h3 className="font-bold text-lg"><code>PUT / PATCH</code></h3>
                        <section className="description p-2">
                            <h4 className="font-bold">Description</h4>
                            <p className="description">Update a todite users settings</p>
                        </section>
                        <section className="headers p-2">
                            <h4 className="font-bold">Headers</h4>
                            <ul>
                                <li>
                                    <code>Authorization</code> - The authorization token generated by Firebase by running <code>user.getIdToken()</code>. <b className="font-bold">Note: This should only be used internally within the app</b>
                                </li>
                            </ul>
                        </section>
                        <section className="query-parameters p-2">
                            <h4 className="font-bold">Query Parameters</h4>
                            <ul>
                                <li>
                                    <code>api_key</code> - <Link href="/docs/api-key"><a className="text-blue-600 hover:underline focus:underline">Your API key</a></Link>
                                </li>
                            </ul>
                        </section>
                        <section className="data-structure p-2">
                            <h4 className="font-bold">Data Structure</h4>
                            <p>This API endpoint returns the updated user with this data structure:</p>
                            <ul>
                                <li>
                                    <code>_id</code> - <code>string</code> - The user's ID (generated by MongoDB)
                                </li>
                                <li>
                                    <code>uid</code> - <code>string</code> - The user's Firebase UID
                                </li>
                                <li>
                                    <code>settings</code> - <code>object</code> (below)
                                    <ul className="p-2">
                                        <li>
                                            <code>theme</code> - <code>string ("dark" | "light" | "system")</code> - The user's preferred theme
                                        </li>
                                        <li>
                                            <code>deleteTodoOnCompleted</code> - <code>boolean</code> - Whether the user wants to-dos to be automatically deleted when they have been completed
                                        </li>
                                        <li>
                                            <code>syncSettings</code> - <code>boolean</code> - Whether the user wants to sync their settings on all devices they sign in on
                                        </li>
                                    </ul>
                                    - The user's site settings
                                </li>
                            </ul>
                        </section>
                        <section className="errors p-2">
                            <h4 className="font-bold">Errors</h4>
                            <p>You may get this error in an <code>error</code> object</p>
                            <ul>
                                <li>
                                    <code>status</code> - <code>number (400 | 404)</code> - The HTTP status code (in a <code>PUT / PATCH</code> request, it can <i>only</i> be <code>400</code> or <code>404</code>)
                                </li>
                                <li>
                                    <code>message</code> - <code>string</code> - An error message
                                </li>
                            </ul>
                        </section>
                    </section>
                    <section>
                        <h3 className="font-bold text-lg"><code>DELETE</code></h3>
                        <section className="description p-2">
                            <h4 className="font-bold">Description</h4>
                            <p className="description">Delete a Todite user and all of their to-dos</p>
                        </section>
                        <section className="headers p-2">
                            <h4 className="font-bold">Headers</h4>
                            <ul>
                                <li>
                                    <code>Authorization</code> - The authorization token generated by Firebase by running <code>user.getIdToken()</code>. <b className="font-bold">Note: This should only be used internally within the app</b>
                                </li>
                            </ul>
                        </section>
                        <section className="query-parameters p-2">
                            <h4 className="font-bold">Query Parameters</h4>
                            <ul>
                                <li>
                                    <code>api_key</code> - <Link href="/docs/api-key"><a className="text-blue-600 hover:underline focus:underline">Your API key</a></Link>
                                </li>
                            </ul>
                        </section>
                        <section className="data-structure p-2">
                            <h4 className="font-bold">Data Structure</h4>
                            <p>This API endpoint returns an object with this data structure:</p>
                            <ul>
                                <li>
                                    <code>success</code> - <code>boolean (true)</code> - Whether the user has been succesfully deleted (the only point of this response is to make sure the client knows the API worked)
                                </li>
                            </ul>
                        </section>
                        <section className="errors p-2">
                            <h4 className="font-bold">Errors</h4>
                            <p>You may get this error in an <code>error</code> object</p>
                            <ul>
                                <li>
                                    <code>status</code> - <code>number (404)</code> - The HTTP status code (in a <code>DELETE</code> request, it can <i>only</i> be <code>404</code>)
                                </li>
                                <li>
                                    <code>message</code> - <code>string</code> - An error message
                                </li>
                            </ul>
                        </section>
                    </section>
                    <section>
                        <h3 className="font-bold text-lg"><code>POST</code></h3>
                        <section className="description p-2">
                            <h4 className="font-bold">Description</h4>
                            <p className="description">Create a Todite user</p>
                        </section>
                        <section className="headers p-2">
                            <h4 className="font-bold">Headers</h4>
                            <ul>
                                <li>
                                    <code>Authorization</code> - The authorization token generated by Firebase by running <code>user.getIdToken()</code>. <b className="font-bold">Note: This should only be used internally within the app</b>
                                </li>
                            </ul>
                        </section>
                        <section className="query-parameters p-2">
                            <h4 className="font-bold">Query Parameters</h4>
                            <ul>
                                <li>
                                    <code>settings</code> (optional) - Your user settings
                                </li>
                            </ul>
                        </section>
                        <section className="data-structure p-2">
                            <h4 className="font-bold">Data Structure</h4>
                            <p>This API endpoint returns an object with this data structure:</p>
                            <ul>
                                <li>
                                    <code>_id</code> - <code>string</code> - The user's ID (generated by MongoDB)
                                </li>
                                <li>
                                    <code>firebaseId</code> - <code>string</code> - The user's Firebase UID
                                </li>
                                <li>
                                    <code>settings</code> - <code>object</code> (below)
                                    <ul className="p-2">
                                        <li>
                                            <code>theme</code> - <code>string ("dark" | "light" | "system")</code> - The user's preferred theme
                                        </li>
                                        <li>
                                            <code>deleteTodoOnCompleted</code> - <code>boolean</code> - Whether the user wants to-dos to be automatically deleted when they have been completed
                                        </li>
                                        <li>
                                            <code>syncSettings</code> - <code>boolean</code> - Whether the user wants to sync their settings on all devices they sign in on
                                        </li>
                                    </ul>
                                    - The user's site settings
                                </li>
                            </ul>
                        </section>
                    </section>
                </section>
                <section id="contributors" className="contributors p-2">
                    <h2 className="font-bold text-2xl"><code>/api/v1/contributors</code></h2>
                    <section>
                        <h3 className="font-bold text-lg"><code>GET</code></h3>
                        <section className="description p-2">
                            <h4 className="font-bold">Description</h4>
                            <p className="description">Get an array of people who have contributed to Todite</p>
                        </section>
                        <section className="data-structure p-2">
                            <h4 className="font-bold">Data Structure</h4>
                            <p>This API endpoint returns an array of objects sorted by whether or not they're me (<Link href="https://github.com/jsmon"><a className="text-blue-600 hover:underline focus:underline">James Simon</a></Link>), and then the number of contributions (in descending order). All objects have this data structure:</p>
                            <ul>
                                <li>
                                    <code>name</code> - <code>string</code> - The contributor's GitHub name, or their GitHub profile
                                </li>
                                <li>
                                    <code>github</code> - <code>string</code> - The contributor's GitHub profile
                                </li>
                                <li>
                                    <code>contributions</code> - <code>number</code> - The number of contributions the contributor has made.
                                </li>
                            </ul>
                        </section>
                    </section>
                </section>
            </main>
        </div>
    );
};

export default ApiDocsV1;
