import React, { useState, useEffect } from 'react';

import Link from 'next/link';

import getSettings from '../../../utils/get-settings';

import { Theme } from '../../../types/settings';

import Header from '../../../components/Header';
import MetaData from '../../../components/MetaData';

const NpmDocsV10 = (): React.ReactElement<{
    children: React.ReactNode;
}, 'div'> => {
    const [theme, setTheme] = useState<Theme>('system');
    useEffect(() => {
        (async () => {
            const settings = await getSettings();
            setTheme(settings.theme);
        })();
    }, []);
    useEffect(() => {
        document.querySelector('html')!.classList.remove('dark', 'light');

        if (theme === 'system') {
            const newTheme = window.matchMedia('(prefers-color-scheme: light)').matches ? 'light' : 'dark';
            document.querySelector('html')!.classList.add(newTheme);
        } else {
            document.querySelector('html')!.classList.add(theme);
        }
    }, [theme]);

    const codeStyle = {
        backgroundColor: '#333842',
        fontFamily: "'Fira Code', Consolas, monospace",
        borderRadius: 5
    };
    const codeKeywordStyle = {
        color: '#C678DD'
    };
    const codeConstantStyle = {
        color: '#D19A66'
    };
    const codeOperatorStyle = {
        color: '#61AFEF'
    };
    const codeStringStyle = {
        color: '#98C379'
    };
    const codeFunctionStyle = {
        color: '#56B6C2'
    };
    

    return (
        <div>
            <MetaData page="api-docs" apiPage="npm" apiVersion="v1.0" />
            <Header page="api-docs" apiPage="npm" apiVersion="v1.0" />
            <main>
                <section id="other-versions" className="other-versions p-2">
                    <h2 className="font-bold text-2xl">Other versions</h2>
                    <ul>
                        <li>
                            <Link href="/docs/npm/v0.1"><a className="text-blue-600 hover:underline focus:underline">v0.1</a></Link>
                        </li>
                    </ul>
                </section>
                <section id="description" className="description p-2">
                    <p><code>todite</code> is an npm package created to let you intergrate your JavaScript / TypeScript projects with Todite.</p>
                </section>
                <section id="installation" className="installation p-2">
                    <h2 className="font-bold text-2xl">Installation</h2>
                    <p>You can install <code>todite</code> using npm:</p>
                    <pre><code>$ npm install todite@latest</code></pre>
                    <p>or yarn:</p>
                    <pre><code>$ yarn add todite@latest</code></pre>
                </section>
                <section id="usage" className="usage p-2">
                    <h2 className="font-bold text-2xl">Usage</h2>
                    <p><code>todite</code> exports a single class that allows you to interact with <Link href="/docs/api/v1"><a className="text-blue-600 hover:underline focus:underline">the API</a></Link> by passing in <Link href="/docs/api-key"><a className="text-blue-600 hover:underline focus:underline">your API key</a></Link>.</p>
                    <pre style={codeStyle}><code><span style={codeKeywordStyle}>const</span> <span style={codeConstantStyle}>Todite</span> <span style={codeOperatorStyle}>= require</span>(<span style={codeStringStyle}>'todite'</span>);
<br />
<span style={codeKeywordStyle}>const</span> <span style={codeConstantStyle}>todite</span> <span style={codeOperatorStyle}>=</span> <span style={codeKeywordStyle}>new</span> <span style={codeFunctionStyle}>Todite</span>(<span style={codeStringStyle}>'your-api-key'</span>);</code></pre>
                </section>
                <section id="types" className="types p-2">
                    <h2 className="font-bold text-2xl">Types</h2>
                    <section className="todo p-2">
                        <h3 className="font-bold text-lg"><code>Todo</code></h3>
                        <p><code>Todo</code> is a type that represents a to-do</p>
                        <ul>
                            <li>
                                <code>_id</code> - <code>string</code> - The to-dos ID (generated by MongoDB)
                            </li>
                            <li>
                                <code>name</code> - <code>string</code> - The to-dos name (what to do)
                            </li>
                            <li>
                                <code>completed</code> - <code>boolean</code> - Whether the to-do has been done
                            </li>
                            <li>
                                <code>user</code> - <code>string</code> - The user's Firebase UID
                            </li>
                            <li>
                                <code>date</code> - <code>Date | undefined</code> When the to-do needs to be done by (or <code>undefined</code>)
                            </li>
                        </ul>
                    </section>
                    <section className="partialtodo p-2">
                        <h3 className="font-bold text-lg"><code>PartialTodo</code></h3>
                        <p><code>PartialTodo</code> is a type that shares all the same properties as <code>Todo</code>, however they can all also be <code>undefined</code>.</p>
                    </section>
                </section>
                <section id="apikeyregex" className="apikeyregex p-2">
                    <h2 className="font-bold text-2xl"><code>todite.apiKeyRegex: RegExp</code></h2>
                    <p>This is a regular expression used to validate an API key.</p>
                </section>
                <section id="create" className="create p-2">
                    <h2 className="font-bold text-2xl"><code>todite.create(&#x7B; name, completed, date &#x7D;: Todo): Promise&lt;Todo&gt;</code></h2>
                    <p>The <code>create()</code> method takes in an object with a <code>name</code>, <code>completed</code> and an (optional) <code>date</code>, and returns a <code>Promise</code> that resolves to the created to-do.</p>
                </section>
                <section id="getall" className="getall p-2">
                    <h2 className="font-bold text-2xl"><code>todite.getAll(): Promise&lt;Todo[]&gt;</code></h2>
                    <p>The <code>getAll()</code> method returns a <code>Promise</code> that resolves to an array of <code>Todo</code>s.</p>
                </section>
                <section id="get" className="get p-2">
                    <h2 className="font-bold text-2xl"><code>todite.get(id: string): Promise&lt;Todo&gt;</code></h2>
                    <p>The <code>get()</code> method takes in an <code>id</code> and returns a <code>Promise</code> that resolves to the <code>Todo</code> with that ID or <code>null</code> if it doesn't exist</p>
                </section>
                <section id="update" className="update p-2">
                    <h2 className="font-bold text-2xl"><code>todite.update(newTodoData: PartialTodo & &#x7B; id: string; &#x7D;): Promise&lt;Todo&gt;</code></h2>
                    <h2 className="font-bold text-2xl">or</h2>
                    <h2 className="font-bold text-2xl"><code>todite.update(id: string, name?: string, completed?: boolean, date?: Date): Promise&lt;Todo&gt;</code></h2>
                    <p>The <code>update()</code> method updates a to-do and returns a <code>Promise</code> that resolves to the updated <code>Todo</code>.</p>
                </section>
                <section id="delete" className="delete p-2">
                    <h2 className="font-bold text-2xl"><code>todite.delete(id: string): Promise&lt;void&gt;</code></h2>
                    <p>The <code>delete()</code> method deletes a to-do and returns a <code>Promise</code> that should resolve with no value</p>
                </section>
            </main>
        </div>
    );
};

export default NpmDocsV10;
